# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 358a50e63c4775c4eaf91f6a8c0e0cbc4a41ae16abfc882114ada60119f336d27022f24872c221506b61d92265537b31e173806285c76084105a016336844f18

test:
  secret_key_base: 48095243de13b0db772637c12f8c295bc0c9389658ac024fb9287defa16cb7320427dd723ab6f8cc29f9d8d3419d49d39a278999d6b887af29615949ba8abfee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
